### ISSUE TITLE
it doesn't work generates error while importing OSError: [WinError 126] The specified module could not be found

### ISSUE THREAD

**Issue by Vikash-Sinha** [oaubert/python-vlc#149]
runfile('D:/python/open cv/untitled0.py', wdir='D:/python/open cv')
Traceback (most recent call last):

  File "D:\python\open cv\untitled0.py", line 7, in <module>
    import vlc

  File "C:\Users\vikas\anaconda3\lib\site-packages\vlc.py", line 210, in <module>
    dll, plugin_path  = find_lib()

  File "C:\Users\vikas\anaconda3\lib\site-packages\vlc.py", line 166, in find_lib
    dll = ctypes.CDLL(libname)

  File "C:\Users\vikas\anaconda3\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)

OSError: [WinError 126] The specified module could not be found

**Comment by oaubert** [comment]
You have to install VLC so that its DLLs are available.
