### ISSUE TITLE
Cannot import vlc after installing VLC 3.0.0

### ISSUE THREAD

**Issue by TokenJan** [oaubert/python-vlc#21]
After I install the vlc 3.0.0 on ubuntu, an error occur when I try to import vlc

```
>>> import vlc
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/vlc.py", line 112, in find_lib
    dll = ctypes.CDLL(p)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/libvlc.so.5: undefined symbol: libvlc_MetaRequest

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/vlc.py", line 173, in <module>
    dll, plugin_path  = find_lib()
  File "/usr/local/lib/python3.5/dist-packages/vlc.py", line 114, in find_lib
    dll = ctypes.CDLL('libvlc.so.5')
  File "/usr/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/libvlc.so.5: undefined symbol: libvlc_MetaRequest
>>> 
```
but the vlc 2.2.2 works well with me, any idea why it happens?

**Comment by oaubert** [comment]
Does vlc 3.0.0 itself work? libvlc_MetaRequest is an internal symbol, which has been renamed to libvlc_MetadataRequest in june 2016, so libvlc.so.5 should not reference it.
