### ISSUE TITLE
OSError: [WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by pawelk1337** [oaubert/python-vlc#219]
error:
```
C:\Program Files (x86)\VideoLAN\VLC>C:/Users/ash/AppData/Local/Programs/Python/Python310/python.exe c:/programing/radio.py
Traceback (most recent call last):
  File "c:\programing\radio.py", line 1, in <module>
    import vlc
  File "C:\Users\ash\AppData\Local\Programs\Python\Python310\lib\site-packages\vlc.py", line 220, in <module>
    dll, plugin_path  = find_lib()
  File "C:\Users\ash\AppData\Local\Programs\Python\Python310\lib\site-packages\vlc.py", line 180, in find_lib
    dll = ctypes.CDLL('.\\' + libname)
  File "C:\Users\ash\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application
```

code:
```
import vlc # ERROR HERE

url = 'https://stream.cheems.dog/listen/two/radio.mp3'
instance = vlc.Instance('--input-repeat=-1', '--fullscreen')
player=instance.media_player_new()
media=instance.media_new(url)
player.set_media(media)
player.play()
```

I dont know whats wrong! 
please help!

**Comment by oaubert** [comment]
Looks like you did not install the VLC app (needed for the DLLs) or a wrong version of it (32 bits on a 64 bits system).

**Comment by AshKetchumPL** [comment]
the vlc is installed its 32x added the folder with execs/dlls in to path
