### ISSUE TITLE
No function error

### ISSUE THREAD

**Issue by lion6230i** [oaubert/python-vlc#24]
`root@OpenWrt:/tmp# python
Python 2.7.9 (default, Jan 24 2017, 15:02:15) 
[GCC 4.8.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import vlc
>>> vlc.libvlc_get_version()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/python_vlc-1.1.2-py2.7.egg/vlc.py", line 3971, in libvlc_get_version
  File "/usr/lib/python2.7/site-packages/python_vlc-1.1.2-py2.7.egg/vlc.py", line 246, in _Cfunction
NameError: no function 'libvlc_get_version'
`

`root@OpenWrt:/tmp# ls /usr/lib/libvlc*
/usr/lib/libvlc.a             /usr/lib/libvlccore.a
/usr/lib/libvlc.so            /usr/lib/libvlccore.so
/usr/lib/libvlc.so.5          /usr/lib/libvlccore.so.8
/usr/lib/libvlc.so.5.5.0      /usr/lib/libvlccore.so.8.0.0`

Does any one know why?
Already have vlc 2.2.4 and can use vlc command to play mp3 on board.

**Comment by lion6230i** [comment]
I found that is cause by find_library.
find_library can't load libvlc.so correctly.
Maybe it's only happen in my board.
Please close it. Thanks!
