### ISSUE TITLE
VLC Import Error

### ISSUE THREAD

**Issue by ComedicChimera** [oaubert/python-vlc#38]
Whenever I try to use python vlc, I get this in my console:

```
  File "mypythonfile.py", line 11, in <module>
    import vlc
  File "C:\Users\forlo\Miniconda3\lib\site-packages\vlc.py", line 198, in <module>
    dll, plugin_path  = find_lib()
  File "C:\Users\forlo\Miniconda3\lib\site-packages\vlc.py", line 173, in find_lib
    dll = ctypes.CDLL(libname)
  File "C:\Users\forlo\Miniconda3\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```

How do I fix this?

**Comment by oaubert** [comment]
It looks like you did not install VLC itself. The python bindings only provide an interface to the libvlc.dll library, so you should install VLC to get the library.

**Comment by joeisme1** [comment]
I am running into this same issue, yet I have vlc installed, and it is the 64-bit version. I have done everything, and I still can't seem to solve it.

**Comment by musindmitriy** [comment]
Running into this same issue with VLC 3.0.8x64 and python 3.7 from Windows 10 Store
```
Traceback (most recent call last):
  File "bot.py", line 5, in <module>
    from player import Player
  File "C:\Users\Дмитрий\SnakeBot\snakebot\player.py", line 5, in <module>
    import vlc
  File "C:\Users\Дмитрий\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\vlc.py", line 207, in <module>
    dll, plugin_path  = find_lib()
  File "C:\Users\Дмитрий\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\vlc.py", line 163, in find_lib
    dll = ctypes.CDLL(libname)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2032.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] Не найден указанный модуль
```

**Comment by aryabhatta000** [comment]
Solution credit [stackoverflow : python-vlc-install-problems](https://stackoverflow.com/questions/42045887/python-vlc-install-problems) 

> [**WinError 126**] resolved with adding folder where libvlc.dll in **system environment - _path_ variable** 
> [**WinError 193**] surfaces - resolved by uninstalling and reinstalling VLC 64bit for Windows
> [VLC BUG] _VLC/lua/playlist/youtube.luac_ requires to be replaced with [youtube.lua](https://github.com/videolan/vlc/blob/master/share/lua/playlist/youtube.lua) file

**Comment by SawonBhattacharya** [comment]
installed python-vlc
currently working on Windows 10 64 bit machine with python 3.7
Also installed VLC for 64 bit machine
But whenever I am trying to import the vlc package it's showing error as following:

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\SAWON\anaconda3\lib\site-packages\vlc.py", line 210, in <module>
    dll, plugin_path  = find_lib()
  File "C:\Users\SAWON\anaconda3\lib\site-packages\vlc.py", line 170, in find_lib
    dll = ctypes.CDLL('.\\' + libname)
  File "C:\Users\SAWON\anaconda3\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found`

I have tried to add libvlc.dll file in the DLLs folder and then added the path of the DLLs folder; but it couldn't help much.
Please help me to debug this

**Comment by mrJean1** [comment]
Check line 170 in your `vlc.py` file, that point is reached when the `plugin-path` can not be found, despite looking in half a dozen places before that, starting at line 140.  The `plugin-path` needs to point to a directory containing plugin optional modules needed by the `libvlc.dll` library.

Try to get around the problem by setting environment variable `PYTHON_VLC_MODULE_PATH` to the `plugin-path` directory, see line 114.

Also, make sure to use `vlc.py` version 3.+ along with the corresponding or a compatible `VLC` 3.+ version.
