### ISSUE TITLE
TypeError: Argument 1 does not allow None as a value

### ISSUE THREAD

**Issue by robfuscator** [oaubert/python-vlc#87]
Hello

I'm working on a GTK frontend for VLC and am experiencing this bug while trying to update my text label that displays the current time:

```
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "/usr/lib/python3.7/site-packages/vlc.py", line 1757, in _callback_handler
    call(event.contents, *args, **kwds)
  File "/path/to/file.py", line 87, in on_time_changed
    GLib.idle_add(self.lbl_current_time.set_text(str(time)))
  File "/usr/lib/python3.7/site-packages/gi/overrides/GLib.py", line 602, in idle_add
    return GLib.idle_add(priority, function, *user_data)
TypeError: Argument 1 does not allow None as a value
```

I'm new to python so I'm not very sure what's going on here. Found this, however, may it helps: https://github.com/quodlibet/quodlibet/issues/2668

**Comment by oaubert** [comment]
idle_add takes a function as parameter, you are passing it the return value of set_text.

**Comment by robfuscator** [comment]
Well, that's embarassing.
Thanks for your fast reply anyways.
